// Known Indonesian gambling domains
export const STATIC_DOMAINS: string[] = [
  // Slot sites
  "slot138.xyz",
  "slot88.site",
  "slotgacor88.com",
  "slotgacor777.com",
  "slot777.site",
  "slotonline88.com",
  "slotmania88.com",
  "slotjudi.com",
  "pragmatic88.com",
  "pragmaticslot.site",
  "maxwin138.com",
  "maxwin777.xyz",
  "maxwin88.site",
  "gacor88.xyz",
  "gacor777.com",
  "gacorslot.site",
  "rtpslot88.com",
  "rtplive.site",
  "rtpgacor.xyz",
  "bocoran-slot.com",
  "pola-slot.site",
  "jamgacor.xyz",
  "akun-pro.site",
  "serverluar.xyz",
  // Togel sites
  "togel88.com",
  "togelhk.site",
  "togelsgp.xyz",
  "togelsydney.com",
  "bandartogel88.com",
  "togelonline.site",
  "prediksi-togel.com",
  "angkajitu88.com",
  "togel4d.site",
  "togelresmi.xyz",
  // Casino online
  "casino88.com",
  "casinoindonesia.site",
  "livecasino88.com",
  "baccaratonline.xyz",
  "rouletteindonesia.com",
  // Sports betting
  "judibola88.com",
  "taruhanbola.site",
  "sbobet88.xyz",
  "mixparlay88.com",
  "bandarjudi88.com",
  // General gambling
  "judionline88.com",
  "situsJudi.site",
  "daftarjudi.xyz",
  "agenjudi88.com",
  "juditerpercaya.com",
  "judiresmi.site",
  "depositjudi.xyz",
  "withdrawcepat.com",
  "bonusnewmember.site",
  "freebet88.com",
  "freechip88.xyz",
  // Poker
  "pokeronline88.com",
  "pokeridn.site",
  "dominoqq88.com",
  "bandarpoker88.xyz",
  // Common patterns with numbers
  "hoki88.com",
  "hoki777.site",
  "jp88.xyz",
  "cuan88.com",
  "cuan777.site",
  "jackpot88.xyz",
  "sultan88.com",
  "sultan777.site",
  "raja88.xyz",
  "raja777.com",
  "king88.site",
  "zeus88.xyz",
  "olympus88.com",
  "gates88.site",
  "starlight88.xyz",
  "bonanza88.com",
  "scatter88.site",
  "wild88.xyz",
  "mega88.com",
  "super88.site",
  "mpo88.xyz",
  "depo88.com",
  "wd88.site",
  "link-alternatif88.xyz",
  "daftar88.com",
  "login88.site",
  "situs88.xyz",
  "agen88.com",
  "bandar88.site",
  "toto88.xyz",
  "toto4d.com",
  "toto4d88.site",

  // ===== INTERNATIONAL GAMBLING SITES =====

  // Major international betting/casino
  "1xbet.com",
  "1xbet.org",
  "1xbet.mobi",
  "1xstavka.ru",
  "bet365.com",
  "bet365.es",
  "betway.com",
  "betway.co.za",
  "888casino.com",
  "888poker.com",
  "888sport.com",
  "williamhill.com",
  "williamhill.es",
  "paddypower.com",
  "bwin.com",
  "bwin.es",
  "unibet.com",
  "unibet.co.uk",
  "betfair.com",
  "betfair.es",
  "pokerstars.com",
  "pokerstars.net",
  "partypoker.com",
  "ladbrokes.com",
  "coral.co.uk",
  "betfred.com",
  "skybet.com",
  "betvictor.com",
  "draftkings.com",
  "fanduel.com",
  "bovada.lv",
  "betonline.ag",
  "mybookie.ag",
  "stake.com",
  "stake.us",
  "rollbit.com",
  "roobet.com",
  "duelbits.com",
  "bc.game",
  "cloudbet.com",
  "bitcasino.io",
  "bitstarz.com",
  "mbitcasino.com",
  "fortunejack.com",
  "fairspin.io",
  "trustdice.win",

  // Asian gambling platforms
  "sbobet.com",
  "sbobet.co",
  "maxbet.com",
  "ibcbet.com",
  "w88.com",
  "m88.com",
  "fun88.com",
  "12bet.com",
  "138.com",
  "dafabet.com",
  "mansion88.com",
  "bk8.com",
  "cmd368.com",
  "citibet.com",

  // Online casino networks
  "casinocom.com",
  "leovegas.com",
  "mrgreen.com",
  "casumo.com",
  "rizk.com",
  "karamba.com",
  "playamo.com",
  "jackpotcity.com",
  "spinpalace.com",
  "royalvegas.com",
  "europacasino.com",
  "casinoeuro.com",
  "betsson.com",
  "nordicbet.com",
  "comeon.com",
  "luckycasino.com",
  "vegascasino.com",
  "slottica.com",
  "vulkanvegas.com",
  "pin-up.casino",
  "1win.com",
  "1win.bet",
  "mostbet.com",
  "mostbet.az",
  "melbet.com",
  "melbet.org",
  "22bet.com",
  "parimatch.com",
  "linebet.com",
  "megapari.com",
  "betwinner.com",

  // Lottery / Togel international
  "lottoland.com",
  "thelotter.com",
  "lotterymaster.com",
  "multilotto.com",
  "jackpot.com",
  "lottomart.com",
];

// Suspicious TLD patterns — domains matching these patterns are likely gambling
export const SUSPICIOUS_PATTERNS: RegExp[] = [
  /slot\d*\.(xyz|site|online|fun|top|click|store|pw|bet|casino)/i,
  /judi\d*\.(xyz|site|online|fun|top|click|store|pw|bet|casino)/i,
  /gacor\d*\.(xyz|site|online|fun|top|click|store|pw|bet|casino)/i,
  /togel\d*\.(xyz|site|online|fun|top|click|store|pw|bet|casino)/i,
  /maxwin\d*\.(xyz|site|online|fun|top|click|store|pw|bet|casino)/i,
  /casino\d*\.(xyz|site|online|fun|top|click|store|pw|bet|casino)/i,
  /poker\d*\.(xyz|site|online|fun|top|click|store|pw|bet|casino)/i,
  /toto\d*\.(xyz|site|online|fun|top|click|store|pw|bet|casino)/i,
  /hoki\d*\.(xyz|site|online|fun|top|click|store|pw|bet|casino)/i,
  /cuan\d*\.(xyz|site|online|fun|top|click|store|pw|bet|casino)/i,
  /jackpot\d*\.(xyz|site|online|fun|top|click|store|pw|bet|casino)/i,
  /sultan\d*\.(xyz|site|online|fun|top|click|store|pw|bet|casino)/i,
  /mpo\d*\.(xyz|site|online|fun|top|click|store|pw|bet|casino)/i,
  /sbobet\d*\.(xyz|site|online|fun|top|click|store|pw|bet|casino)/i,
  /pragmatic[\-_]?\d*\.(xyz|site|online|fun|top|click|store|pw|bet|casino)/i,
  /rtp[\-_]?(live|slot)\d*\.(xyz|site|online|fun|top|click|store|pw|bet|casino)/i,
  /bandar[\-_]?\d*\.(xyz|site|online|fun|top|click|store|pw|bet|casino)/i,
  /agen[\-_]?\d*\.(xyz|site|online|fun|top|click|store|pw|bet|casino)/i,
  // International patterns
  /bet\d+\.(com|net|org|io|co|ag|lv)/i,
  /casino\d*\.(com|net|org|io|co)/i,
  /poker\d*\.(com|net|org|io|co)/i,
  /gambling\d*\.(com|net|org|io|co)/i,
  /\d*xbet\.(com|net|org|io|mobi)/i,
  /spin\d*\.(com|io|casino|bet)/i,
];

// URL path keywords that indicate gambling content
export const URL_KEYWORD_PATTERNS: RegExp[] = [
  // Indonesian
  /slot[\-_]?gacor/i,
  /maxwin/i,
  /pragmatic[\-_]?play/i,
  /link[\-_]?alternatif/i,
  /rtp[\-_]?live/i,
  /bocoran[\-_]?slot/i,
  /pola[\-_]?slot/i,
  /jam[\-_]?gacor/i,
  /akun[\-_]?pro/i,
  /server[\-_]?luar/i,
  /daftar[\-_]?slot/i,
  /deposit[\-_]?(slot|judi|togel)/i,
  /bandar[\-_]?togel/i,
  /scatter[\-_]?hitam/i,
  /freebet/i,
  /freechip/i,
  /bonus[\-_]?new[\-_]?member/i,
  // International
  /online[\-_]?casino/i,
  /sports[\-_]?betting/i,
  /live[\-_]?betting/i,
  /slot[\-_]?machine/i,
  /roulette[\-_]?online/i,
  /blackjack[\-_]?online/i,
  /baccarat[\-_]?online/i,
];

// International gambling keywords for image/ad filtering
export const GAMBLING_IMAGE_KEYWORDS: string[] = [
  // Indonesian
  "slot", "judi", "togel", "casino", "gacor", "maxwin",
  "pragmatic", "sbobet", "poker", "bandar", "toto",
  "deposit", "freebet", "freechip", "scatter",
  // International
  "1xbet", "bet365", "betway", "888casino", "pokerstars",
  "draftkings", "fanduel", "stake", "roobet", "gambling",
  "betting", "jackpot", "roulette", "blackjack", "baccarat",
  "sports-bet", "sportbet", "livecasino", "live-casino",
  "spin-win", "free-spins", "bonus-casino", "welcome-bonus",
];
